name: Build Docker Images

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile*'
      - '.github/workflows/*'

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          echo "Finding Dockerfiles..."
          FILES=$(find . -type f -name 'Dockerfile*' | jq -R -s -c 'split("\n")[:-1]')
          echo "::set-output name=matrix::{\"include\": ${FILES}}"

  build:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build -f ${{ matrix.include }} -t my-image:${{ matrix.include }} .
